


name: Azure vm deployer

on:
  push:
    branches: [deploy-prod]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2

      - name: Depoly and restart web server
        run: |
          cd server
          npm install
          PORT=80 JWT_SECRET=12345 PASSWORD_SALT=codersquare ENV=production npm run start:prod


